services:
  postgis:
    build:
      context: ./postgis
      dockerfile: Dockerfile
    container_name: "gpx4run-postgis"
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped

  osrm-frontend:
    image: osrm/osrm-frontend
    container_name: "osrm-frontend"
    ports:
      - "9966:9966"
    environment:
      - OSRM_BACKEND=http://osrm-backend:6000

  osrm-backend:
    image: osrm/osrm-backend
    container_name: "gpx4run-osrm"
    volumes:
      - ~/Documents/custom_osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: bash -c "
      osrm-extract -p /profiles/foot.lua /data/strava.osm
      && osrm-partition /data/strava.osrm
      && osrm-customize /data/strava.osrm
      && osrm-routed --algorithm mld /data/strava.osrm
      "
  




networks:
  default:
    driver: bridge