services:
  postgis:
    build:
      context: ./postgis
      dockerfile: Dockerfile
    container_name: "gpx4run-postgis"
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped

  osrm-backend:
    image: osrm/osrm-backend
    container_name: "gpx4run-osrm"
    volumes:
      - ~/Documents/custom_osm:/data
      - ./profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: bash -c "
      osrm-extract -l INFO -p /profiles/foot.lua /data/strava.osm
      && osrm-partition -l INFO /data/strava.osrm
      && osrm-customize -l INFO /data/strava.osrm
      && osrm-routed -l INFO --algorithm mld /data/strava.osrm
      "
  




networks:
  default:
    driver: bridge